//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipTracking.Generic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShipTracking.Generic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ship detail successfully..
        /// </summary>
        public static string AddShipDetailSuccessfully {
            get {
                return ResourceManager.GetString("AddShipDetailSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add ship track detail successfully..
        /// </summary>
        public static string AddShipTrackDetailSuccessfully {
            get {
                return ResourceManager.GetString("AddShipTrackDetailSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Time is required..
        /// </summary>
        public static string DepartureTimeRequired {
            get {
                return ResourceManager.GetString("DepartureTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something went wrong. We&apos;re working on getting this fixed as soon as we can. You may be able to try again..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid ship type.
        /// </summary>
        public static string InvalidShipType {
            get {
                return ResourceManager.GetString("InvalidShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid speed.
        /// </summary>
        public static string InvalidSpeed {
            get {
                return ResourceManager.GetString("InvalidSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port doesn&apos;t exists in system..
        /// </summary>
        public static string PortIdRequired {
            get {
                return ResourceManager.GetString("PortIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship already reached at destination port..
        /// </summary>
        public static string ShipAlreadyReachedAtDestionationPort {
            get {
                return ResourceManager.GetString("ShipAlreadyReachedAtDestionationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship departure time must be future time..
        /// </summary>
        public static string ShipDepartureTimeInvalid {
            get {
                return ResourceManager.GetString("ShipDepartureTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship doesn&apos;t exists in system..
        /// </summary>
        public static string ShipIdRequired {
            get {
                return ResourceManager.GetString("ShipIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship is still at anchor..
        /// </summary>
        public static string ShipNotStartedYet {
            get {
                return ResourceManager.GetString("ShipNotStartedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update ship detail successfully..
        /// </summary>
        public static string UpdateShipDetailSuccessfully {
            get {
                return ResourceManager.GetString("UpdateShipDetailSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship status updated successfully..
        /// </summary>
        public static string UpdateShipStatusSuccessfully {
            get {
                return ResourceManager.GetString("UpdateShipStatusSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update velocity details successfully..
        /// </summary>
        public static string UpdateShipVelocityDetail {
            get {
                return ResourceManager.GetString("UpdateShipVelocityDetail", resourceCulture);
            }
        }
    }
}
